import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cellma4testing.riomed.com/cellmaUser/login');
  await page.getByTestId('Username').click();
  await page.getByTestId('Username').fill('prerelease.auto');
  await page.getByTestId('Password').click();
  await page.getByTestId('Password').fill('Manoj@2023');
  await page.getByTestId('Login').click();
  await page.getByTestId('Patients').click();


  await page.getByTestId('Given Name').click();
  await page.getByTestId('Given Name').fill('Akshay');
  await page.getByTestId('Family Name').click();
  await page.getByTestId('Family Name').fill('Riomedtest');
  await page.getByTestId('Sex').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.getByLabel('Choose date').click();
  await page.getByLabel('calendar view is open, switch').click();
  await page.getByRole('button', { name: '1993' }).click();
  await page.getByLabel('Mar 5,').click();
  await page.getByTestId('Search').click();
  await page.getByTestId('Add Patient').click();
  await page.getByTestId('uniqueIdentification').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Aadhar Card' }).click();
  await page.getByTestId('Unique Identification ID').click();
  await page.getByTestId('Unique Identification ID').fill('987465412102');
  await page.getByTestId('photoIdentification').getByLabel('Open').click();
  await page.getByRole('option', { name: 'PAN Card' }).click();
  await page.getByTestId('Photo Identification ID').click();
  await page.getByTestId('Photo Identification ID').fill('Ajaok1884P');
  await page.getByTestId('issuingCountry').getByLabel('Open').click();
  await page.getByRole('option', { name: 'India', exact: true }).click();
  await page.getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Mr', exact: true }).click();
  await page.getByTestId('Middle Name(s)').click();
  await page.getByTestId('Middle Name(s)').fill('Test');
  await page.getByTestId('Maiden Name').click();
  await page.getByTestId('Maiden Name').fill('Pune');
  await page.getByTestId('Mobile').click();
  await page.getByTestId('Mobile').fill('9762713710');
  await page.getByTestId('Email').click();
  await page.getByTestId('Email').fill('maheshRiomed27@gmail.com');
  await page.getByTestId('Duplicate Check').click();
  await page.getByTestId('Create Patient').click();
  await page.getByTestId('Marital Status').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Single' }).click();
  await page.getByTestId('Sexual Orientation').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Heterosexuality' }).click();
  await page.getByTestId('County Of Birth').click();
  await page.getByTestId('County Of Birth').fill('Maharashtra');
  await page.getByTestId('Ethnicity').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Indian' }).click();
  await page.getByTestId('Occupation').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Trainer' }).click();
  await page.getByTestId('Religion').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Hindu' }).click();
  await page.getByTestId('Town Of Birth').click();
  await page.getByTestId('Town Of Birth').fill('Pune');
  await page.getByTestId('Country Of Birth').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'India', exact: true }).click();
  await page.getByTestId('Nationality').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Indian' }).click();
  await page.getByTestId('Primary Disability').getByLabel('​', { exact: true }).click();
  await page.getByRole('checkbox').check();
  await page.locator('#menu-primaryDisability > .MuiBackdrop-root').click();
  await page.getByTestId('Primary Disability').getByLabel('No').click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByRole('checkbox').check();
  await page.locator('#menu-primaryDisability > .MuiBackdrop-root').click();
  await page.getByTestId('Assistance Needed').click();
  await page.getByTestId('Assistance Needed').fill('No');
  await page.getByTestId('Language').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Hindi' }).click();
  await page.getByTestId('Interpreter Type').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Whisper' }).click();
  await page.getByTestId('Hospital Ref').click();
  await page.getByTestId('Hospital Ref').fill('AutoHospRef001');
  await page.getByTestId('Patient Type').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Regular' }).click();
  await page.getByTestId('Prisoner').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByTestId('Blood Type').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'B+', exact: true }).click();
  await page.getByTestId('Patient Web Access').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByTestId('Notes').click();
  await page.getByTestId('Notes').fill('testing');
  await page.getByTestId('Next').click();
  await page.locator('#numberRoadPermanentAddress').click();
  await page.locator('#numberRoadPermanentAddress').fill('15 number');
  await page.locator('#townPermanentAddress').click();
  await page.locator('#townPermanentAddress').fill('Hadapsar');
  await page.locator('#districtPermanentAddress').click();
  await page.locator('#districtPermanentAddress').fill('Pune');
  await page.locator('#countyPermanentAddress').fill('Maha');
  await page.locator('#countyPermanentAddress').click();
  await page.locator('#countyPermanentAddress').fill('Maharashtra');
  await page.locator('#postCodePermanentAddress').fill('4110');
  await page.locator('#postCodePermanentAddress').click();
  await page.locator('#postCodePermanentAddress').fill('411028');
  await page.getByTestId('Find Postcode').first().click();
  await page.getByTestId('CommonCellmaPopup').getByTestId('Country').click();
  await page.getByTestId('CommonCellmaPopup').getByTestId('Country').fill('India');
  await page.getByTestId('CommonCellmaPopup').getByTestId('Save').click();
  await page.locator('#iSOCountryCodePermanentAddress').click();
  await page.locator('#iSOCountryCodePermanentAddress').fill('93');
  await page.locator('#iCAOCountryCodePermanentAddress').click();
  await page.locator('#iCAOCountryCodePermanentAddress').fill('1325');
  await page.locator('#phonePermanentAddress').click();
  await page.locator('#phonePermanentAddress').fill('02026991584');
  await page.locator('#workPhonePermanentAddress').click();
  await page.locator('#workPhonePermanentAddress').fill('02025415');
  await page.locator('#faxPermanentAddress').click();
  await page.locator('#faxPermanentAddress').fill('020215436');
  await page.locator('#mui-component-select-healthRegion').click();
  await page.getByRole('option', { name: 'Dadra And Nagar Haveli' }).click();
  await page.locator('#mui-component-select-locationZone').click();
  await page.getByRole('option', { name: 'Zone' }).click();
  await page.locator('input[name="tempNumberRoad"]').click();
  await page.locator('input[name="tempNumberRoad"]').fill('15 number');
  await page.locator('input[name="tempTown"]').click();
  await page.locator('input[name="tempTown"]').fill('Hadapsar');
  await page.locator('input[name="tempDistrict"]').click();
  await page.locator('input[name="tempDistrict"]').fill('Pune');
  await page.locator('input[name="tempCounty"]').click();
  await page.locator('input[name="tempCounty"]').fill('Maharashtra');
  await page.locator('input[name="tempPostcode"]').click();
  await page.locator('input[name="tempPostcode"]').fill('411028');
  await page.getByTestId('Find Postcode').nth(1).click();
  await page.getByTestId('CommonCellmaPopup').getByTestId('Country').click();
  await page.getByTestId('CommonCellmaPopup').getByTestId('Country').fill('India');
  await page.getByTestId('CommonCellmaPopup').getByTestId('Save').click();
  await page.locator('input[name="tempISOCountryCode"]').click();
  await page.locator('input[name="tempISOCountryCode"]').fill('93');
  await page.locator('input[name="tempICAOCountryCode"]').click();
  await page.locator('input[name="tempICAOCountryCode"]').fill('1324');
  await page.locator('input[name="tempPhone"]').click();
  await page.locator('input[name="tempPhone"]').fill('02026995154');
  await page.locator('input[name="tempEmail"]').click();
  await page.locator('input[name="tempEmail"]').fill('testadd@gmail.com');
  await page.locator('#temporaryMobileNumber').click();
  await page.locator('#temporaryMobileNumber').fill('9854198001');
  await page.locator('input[name="tempWorkPhone"]').click();
  await page.locator('input[name="tempWorkPhone"]').fill('02026991548');
  await page.locator('input[name="tempFax"]').click();
  await page.locator('input[name="tempFax"]').fill('0202514454');
  await page.locator('#mui-component-select-tempHealthRegion').click();
  await page.getByRole('option', { name: 'Dadra And Nagar Haveli' }).click();
  await page.getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Zone' }).click();
  await page.getByTestId('TA Billing Correspondence').getByLabel('A').check();
  await page.getByTestId('Start Date').getByLabel('Choose date').click();
  await page.getByLabel('Mar 1,').click();
  await page.getByTestId('End Date').getByLabel('Choose date').click();
  await page.getByLabel('Mar 21,').click();
  await page.getByTestId('Save').click();
  await page.getByTestId('Title').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Mr', exact: true }).click();
  await page.getByTestId('Family Name').click();
  await page.getByTestId('Family Name').fill('Riomedtest');
  await page.getByTestId('Given Name').click();
  await page.getByTestId('Given Name').fill('Sagar');
  await page.getByTestId('Middle Name(s)').click();
  await page.getByTestId('Middle Name(s)').fill('test');
  await page.getByTestId('Born').getByLabel('Choose date').click();
  await page.getByLabel('calendar view is open, switch').click();
  await page.getByRole('button', { name: '1994' }).click();
  await page.getByLabel('Mar 8,').click();
  await page.getByTestId('Ethnicity').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Indian' }).click();
  await page.getByTestId('Occupation').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Trainer' }).click();
  await page.getByTestId('Mobile').click();
  await page.getByTestId('Mobile').fill('9890098900');
  await page.getByTestId('Email').click();
  await page.getByTestId('Email').fill('sagarriomed93@gmail.com');
  await page.getByTestId('Relationship').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Brother' }).click();
  await page.getByTestId('Next of Kin').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByTestId('Identifier Type').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Aadhar Card' }).click();
  await page.getByTestId('Identifier Number').click();
  await page.getByTestId('Identifier Number').fill('654987654987');
  await page.getByTestId('Professional Title').click();
  await page.getByTestId('Professional Title').fill('Mr');
  await page.getByTestId('Receive Patient Letters').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByRole('checkbox', { name: 'Send Patient Text/Email' }).check();
  await page.getByRole('checkbox', { name: 'Is Referrer' }).check();
  await page.getByLabel('Notes').click();
  await page.getByLabel('Notes').fill('Added PIP for testing');
  await page.getByRole('checkbox', { name: 'Assisting in partner\'s care' }).check();
  await page.getByRole('checkbox', { name: 'For use on the University' }).check();
  await page.getByTestId('Save').click();
  await page.getByTestId('Next').click();
  await page.getByTestId('Search').click();
  await page.getByLabel('Search').click();
  await page.getByLabel('Search').fill('bates');
  await page.getByLabel('personAdd').click();
  await page.getByTestId('Next').click();
  await page.getByTestId('PhotoCameraIcon').click();
  await page.locator('body').setInputFiles('Patient.png');
  await page.getByTestId('Upload').click();
  await page.getByTestId('Print ID Card').click();
  await page.getByTestId('Save').click();
  await page.getByTestId('Menu').click();
  await page.getByText('Add Referral').click();
  await page.getByTestId('Received Referral Date').getByLabel('Choose date').click();
  await page.getByLabel('Mar 18,').click();
  await page.getByTestId('Approved Referral Date').getByLabel('Choose date').click();
  await page.getByLabel('Mar 19,').click();
  await page.getByTestId('Date of Referral').getByLabel('Choose date').click();
  await page.getByLabel('Mar 19, 2024', { exact: true }).click();
  await page.getByTestId('Time of Referral').getByLabel('Choose time').click();
  await page.locator('.css-1umqo6f').click();
  await page.locator('.css-1umqo6f').click();
  await page.getByTestId('Source of Referral').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Self' }).click();
  await page.getByTestId('referralType').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Clinical' }).click();
  await page.getByTestId('referralReason').getByLabel('Open').click();
  await page.getByRole('option', { name: 'In Patient' }).click();
  await page.getByTestId('Mode of Referral').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Email' }).click();
  await page.getByTestId('Service').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'General Medicine Automation' }).click();
  await page.getByTestId('Clinic Type').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Cardiology' }).click();
  await page.getByTestId('clinicLocation').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Cardio Location' }).click();
  await page.getByTestId('team').getByLabel('Open').click();
  await page.getByRole('option', { name: 'HP Region1' }).click();
  await page.getByTestId('patientCare').getByLabel('Open').click();
  await page.getByRole('option', { name: 'In Patient' }).click();
  await page.getByTestId('Preferred Sex for Assessment').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.getByTestId('Consultant').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Mr Prerelease AutoEst' }).click();
  await page.getByTestId('methodOfArrival').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Car' }).click();
  await page.getByTestId('Time of Arrival').getByLabel('Choose time').click();
  await page.locator('.css-1umqo6f').click();
  await page.locator('.css-1umqo6f').click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('Playwright Documentation.docx');
  await page.getByTestId('Add Additional Documents').click();
  await page.locator('textarea[name="notes"]').click();
  await page.locator('textarea[name="notes"]').fill('added for testing');
  await page.getByTestId('Save').click();
  await page.getByTestId('Menu').click();
  await page.getByTestId('menuDropDownLogout').click();
});