import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cellma4testing.riomed.com/cellmaUser/login');
  await page.getByTestId('Username').click();
  await page.getByTestId('Username').fill('prerelease.auto');
  await page.getByTestId('Password').click();
  await page.getByTestId('Password').fill('Manoj@2023');
  await page.getByTestId('Login').click();
  await page.getByTestId('Appointments').click();
  await page.getByTestId('Given Name').click();
  await page.getByTestId('Given Name').fill('amit');
  await page.getByTestId('Family Name').click();
  await page.getByTestId('Family Name').fill('riomedpune');
  await page.getByTestId('Search').click();
  await page.getByTestId('Select').click();
  await page.getByTestId('Confirm Existing Details').click();
  await page.getByTestId('Received Referral Date').getByLabel('Choose date').click();
  await page.getByLabel('Mar 5,').click();
  await page.getByTestId('Approved Referral Date').getByLabel('Choose date').click();
  await page.getByLabel('Mar 5, 2024', { exact: true }).click();
  await page.getByTestId('Date of Referral').getByLabel('Choose date').click();
  await page.getByLabel('Mar 6,').click();
  await page.getByTestId('Time of Referral').getByLabel('Choose time').click();
  await page.locator('.css-1umqo6f').click();
  await page.locator('.css-1umqo6f').click();
  await page.getByTestId('Source of Referral').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Self' }).click();
  await page.getByTestId('referralType').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Clinical' }).click();
  await page.getByTestId('referralReason').getByLabel('Open').click();
  await page.getByRole('option', { name: 'In Patient' }).click();
  await page.getByTestId('Mode of Referral').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Email' }).click();
  await page.getByTestId('Service').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'General Medicine Automation' }).click();
  await page.getByTestId('Clinic Type').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Cardiology' }).click();
  await page.getByTestId('clinicLocation').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Cath Lab Location' }).click();
  await page.getByTestId('team').getByLabel('Open').click();
  await page.getByRole('option', { name: 'HP Region1' }).click();
  await page.getByTestId('Preferred Sex for Assessment').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.getByTestId('Consultant').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Mr Prerelease AutoEst' }).click();
  await page.getByTestId('methodOfArrival').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Ambulance' }).click();
  await page.getByTestId('Time of Arrival').getByLabel('Choose time').click();
  await page.locator('.css-1umqo6f').click();
  await page.locator('.css-1umqo6f').click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('Playwright Documentation.docx');
  await page.locator('#notesReferralLetter0').click();
  await page.locator('#notesReferralLetter0').fill('test');
  await page.getByTestId('Add Additional Documents').click();
  await page.getByLabel('Await Referral Acceptance').check();
  await page.locator('textarea[name="notes"]').click();
  await page.locator('textarea[name="notes"]').fill('testing');
  await page.getByTestId('Save').click();
  await page.getByLabel('cellmaImageAvatar').click();
  await page.getByTestId('Menu').click();
  await page.getByTestId('menuDropDownLogout').click();
});